version: "3.9"
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant
    volumes:
      - ${CONFIG_PATH}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY=${TAIL_SCALE_AUTH_KEY}
      - TS_ROUTES=192.168.1.0/24
      - TS_STATE_DIR=/var/lib
      - TS_EXTRA_ARGS= --advertise-exit-node --accept-routes
    volumes:
      - ${CONFIG_PATH}/tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun

  vpn:
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY=${NORD_VPN_PRIVATE_KEY}
      - NET_LOCAL=192.168.1.0/24
    restart: unless-stopped
    ports:
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 9696:9696 # prowlarr
      - 9091:9091 # transmission
      - 51413:51413 # also transmission?
      - 51413:51413/udp

  transmission:
    image: ghcr.io/linuxserver/transmission
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # - USER=username #optional
      # - PASS=password #optional
      # - WHITELIST=iplist #optional
      # - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ${CONFIG_PATH}/transmission:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DOWNLOADS_PATH}/transmissionwatch:/watch
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
    - ${CONFIG_PATH}/prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${TV_PATH}:/tv #optional
      - ${DOWNLOADS_PATH}:/downloads #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MOVIE_PATH}:/movies #optional
      - ${DOWNLOADS_PATH}:/downloads #optional
    restart: unless-stopped

  miniflux:
    image: miniflux/miniflux
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      minifluxdb:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@minifluxdb/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${MINIFLUX_USER}
      - ADMIN_PASSWORD=${MINIFLUX_PASS}

  minifluxdb:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - ${CONFIG_PATH}/miniflux/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

  adguardhome:
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - ${LOCAL_IP}:53:53/udp # https://discourse.pi-hole.net/t/solve-dns-resolution-in-other-containers-when-using-docker-pihole/31413
      - 3000:3000/tcp
      - 8081:80/tcp
      - 8443:443/tcp
    volumes:
      - ${CONFIG_PATH}/adguard/work:/opt/adguardhome/work
      - ${CONFIG_PATH}/adguard/config:/opt/adguardhome/conf
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
    volumes:
      - ${CONFIG_PATH}/plex:/config
      - ${TV_PATH}:/tv #optional
      - ${MOVIE_PATH}:/movies #optional
    devices:
       - /dev/dri:/dev/dri # For H/W transcoding
    restart: unless-stopped

  komga:
    image: gotson/komga
    volumes:
      - ${CONFIG_PATH}/komga/config:/config
      - ${BOOKS_PATH}:/data #optional
    ports:
      - 25600:25600
    user: "1000:1000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --cleanup
    restart: unless-stopped
    environment:
      - WATCHTOWER_NOTIFICATION_URL=discord://${DISCORD_TOKEN}@${DISCORD_WEB_HOOK_ID}?Username=Watchtower
      - WATCHTOWER_SCHEDULE="30 2 * * *"

  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}

  uptime-kuma:
    image: louislam/uptime-kuma
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001

  portainer:
    image: portainer/portainer-ce
    ports:
      - 9443:9443
      - 9000:9000
    volumes:
      - ${CONFIG_PATH}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  glances:
    image: nicolargo/glances
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    environment:
      - "GLANCES_OPT=-w"
      - TZ=America/Los_Angeles
    restart: unless-stopped

  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_PATH}/smokeping/config:/config
      - ${CONFIG_PATH}/smokeping/data:/data
    ports:
      - 8321:80
    restart: unless-stopped

  homer:
    image: b4bz/homer
    volumes:
      - ${CONFIG_PATH}/homer:/www/assets
    ports:
      - 80:8080
    restart: unless-stopped
